### ISSUE TITLE
Sattrack dosen't work longer

### ISSUE THREAD

**Issue by bernemer** [Hopperpop/Sattrack#8]
Hi,
my Sattrack ESP-01 dosen't work longer.
I build it in 2018 and it works very fine. One year later i get only a red flashing ring.
Power on
2 red led
2 orange led
red blinking ring.

I use: de.pool.ntp.org (my router works fine with this ntp)
Noradid for ISS: 25544

i flashed it again with the latest code and get the same error
Ardurio 1.8.5 core 2.3.0 and 2.4.1 testet.

Any idea?

**Comment by bernemer** [comment]
I think its a problem with the TLE.

debug result:
connected with Test, channel 9
dhcp client start...
ip:192.168.0.61,mask:255.255.255.0,gw:192.168.0.1
.
Local IP address: 192.168.0.61

mDNS responder started for Sattrack.local

sending NTP packet...
NTP packet received, length=48
Current time: 19/12/2019 12:3:16.00
GET /satcat/tle.php?CATNR=25544 HTTP/1.1
Host: celestrak.com
Connection: close


Can't get data

[WS-Server] Server Started.
Looprate:37476 FreeMem:21360 

any idea to fix it?

**Comment by Lenbok** [comment]
It looks like the celestrak server output has changed:

```
$ wget -q -O - http://celestrak.com/satcat/tle.php?CATNR=25544
ISS (ZARYA)
1 25544U 98067A   20005.58853759  .00001026  00000-0  26357-4 0  9993
2 25544  51.6453  77.9782 0005202 102.5065  46.3610 15.49539649206658
```

The current parsing code https://github.com/Hopperpop/Sattrack/blob/12641a674d9a90c92e51c946803ac3a7a8025f87/src/Clients.h#L120 is expecting the output to be wrapped in `<pre>` tags, which is no longer true, so it needs to be updated.

**Comment by bernemer** [comment]
Thank‘s for the answer.
I will test it next week.

**Comment by bernemer** [comment]
Hi Lenbok,
thanks for finding the problem.
<pre> tag is missing.
i updatet the row 120 to:
if ( line == "" ){ 
because the first output before ISS (ZARYA) is an empty row.
So it works for the ISS.

**Comment by Lenbok** [comment]
@bernemer Can you please submit a PR?

**Comment by bernemer** [comment]
@Lenbok what du you mean with PR?
I'm beginner with github und programming.

**Comment by Lenbok** [comment]
@bernemer PR stands for Pull Request. It means that on your local git copy of the repository (where you have made the change), you commit it on a branch, hen push to your fork of the repository on github, then make a pull request to this repository so that either @Hopperpop can merge it in, or others can see it and pull it themselves to get the fix without having to manually make the change.

**Comment by Hopperpop** [comment]
I'm almost done with a fix that hopefully is more robust. Instead of parsing the html body (which can change and already changed in the past), it uses a pattern to see if it match a tle. I try to push it this week.

**Comment by Hopperpop** [comment]
Try https://github.com/Hopperpop/Sattrack/commit/811dd4a6ba8f9b45e9df03b7a028cb202b9c82d6.
Note: Needed to make some modification to let it work with the newer neopixel library. You can update the lib or replace 'NeoEsp8266Uart1800KbpsMethod' with the older 'NeoEsp8266Uart800KbpsMethod'.
