### ISSUE TITLE
Orbit seems to be incorrect

### ISSUE THREAD

**Issue by nliviu** [Hopperpop/Sattrack#9]
![Screenshot 2021-10-09 at 17 49 30](https://user-images.githubusercontent.com/4199039/136662987-5ea6775a-5540-4d3a-9f0a-4602559b2a95.png)
Screenshot taken today, local time in Romania.

**Comment by Hopperpop** [comment]
Can you provide more information on what looks wrong?

**Comment by nliviu** [comment]
I would expect the orbit trace to be continous.

**Comment by Hopperpop** [comment]
A satellites orbit doesn't come back to the same point each turn. If more points where drawn it would look more like this:
https://upload.wikimedia.org/wikipedia/commons/a/aa/ISS_orbits_04132013.jpg

The gab is normal.

**Comment by nliviu** [comment]
Ok. I understand now.
Thank you!
